@startuml CU_01_Seguridad_Usuarios
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Usuario Visitante" as user_anon
actor "Clienta" as clienta
actor "Administradora" as admin

clienta -up-|> user_anon

rectangle "Módulo 1: Seguridad y Usuarios" {
    usecase "CU-001: Iniciar Sesión (RBAC)" as CU01
    usecase "CU-002: Registrarse como Clienta" as CU02
    usecase "CU-003: Recuperar Contraseña" as CU03
    usecase "CU-004: Consultar y Modificar Perfil" as CU04
    usecase "CU-005: Gestionar Personal y Roles (CRUD)" as CU05
    usecase "Validar Credenciales y Hash" as CU_Val
    usecase "Auditar Acceso (auditoria)" as CU_Log
    usecase "Desactivar Personal (Baja Lógica)" as CU_Desact
    usecase "Registrar Traza Crítica" as CU_Audit

    CU01 ..> CU_Val : <<include>>
    CU01 ..> CU_Log : <<include>>
    CU01 <.. CU03 : <<extend>> \n (Olvido de contraseña)
    CU05 <.. CU_Desact : <<extend>> \n (Si es baja lógica)
    CU05 ..> CU_Audit : <<include>>
}

user_anon --> CU01
user_anon --> CU02
clienta --> CU04
admin --> CU05
@enduml