@startmindmap
!theme crt-amber
skinparam linetype ortho
skinparam classAttributeIconSize 0

* G.C.L. OneStyle Mariana\n(E-commerce & OMS)

** Acceso y Seguridad
*** Registro Público (Rol Clienta por Defecto)
*** Inicio de Sesión RBAC (Clienta, Vendedora, Administradora)
*** Recuperación Segura de Credenciales (Token Temporal)

** Tienda Pública y Clientas
*** Catálogo Dinámico de Productos
**** Exploración Paginada y Filtros por Categoría
**** Buscador Predictivo por Nombre
**** Detalle de Prenda (Vista_Detalle_Producto)
***** Galería de Imágenes
***** Selector de Variantes (Talla y Color)
*** Carrito de Compras
**** Validación y Reserva Temporal de Stock
**** Modificación de Cantidades y Recálculo Dinámico
*** Checkout y Despacho
**** Captura de Dirección de Envío (domicilio)
**** Confirmación Asistida y Redirección con Payload a WhatsApp
*** Área Privada de Clienta (Autenticado)
**** Perfil y Direcciones Predeterminadas
**** Historial de Pedidos y Trazabilidad de Estados
*** Centro de Ayuda al Cliente
**** Consulta Pública de FAQ por Categorías
**** Canales Oficiales de Soporte y Contacto

** Panel Administrativo y Operativo (Back-office)
*** Dashboard Ejecutivo
**** Indicadores de Ventas y Rendimiento por Vendedora
**** Monitoreo de Alertas de Reposición (Stock Crítico)
*** Gestión de Catálogo e Inventario
**** Mantenimiento CRUD de Prendas y Categorías
**** Parametrización de Variantes (Matriz Tallas, Colores y Stock)
**** Control de Visibilidad (Baja Lógica / Soft Delete)
*** Gestión de Pedidos y Logística (OMS)
**** Bandeja General de Órdenes y Asignación de Vendedora
**** Verificación de Comprobante de Pago (WhatsApp)
**** Control de Estados (Registrado, En Empaque, Despachado, Cancelado)
*** Administración de Usuarios y Personal
**** CRUD de Personal Operativo (Vendedoras)
**** Asignación de Roles y Bajas Lógicas de Cuentas
*** Configuración, Soporte y Auditoría
**** Mantenimiento del Centro de Ayuda (FAQ y Contacto)
**** Visor Inmutable de Logs de Auditoría (Cambios Críticos)

@endmindmap
