@startmindmap
!theme crt-amber
skinparam linetype ortho
skinparam classAttributeIconSize 0

* G.C.L. OneStyle Mariana\n(E-commerce & OMS)

** Acceso y Autenticación
*** Registro Público (Clientas)
*** Inicio de Sesión RBAC (Clienta, Vendedora, Administradora)
*** Recuperación de Contraseña (Token Temporal)

** Tienda Pública y Clientas (Front-office)
*** Catálogo Dinámico de Productos
**** Exploración Paginada y Filtros por Categoría
**** Buscador Predictivo por Nombre
**** Detalle de Prenda (Vista_Detalle_Producto)
***** Galería de Imágenes
***** Selector de Variantes (Talla y Color)
*** Carrito de Compras
**** Validación y Reserva Temporal de Stock
**** Modificación de Cantidades y Recálculo Dinámico
*** Checkout y Despacho
**** Formulario de Entrega (Captura de Domicilio)
**** Confirmación Asistida y Redirección a WhatsApp
*** Área Privada de Clienta
**** Mi Perfil y Direcciones
**** Historial de Pedidos y Rastreo de Estados
*** Centro de Ayuda
**** Consulta Pública de FAQ por Categorías
**** Canales Oficiales de Soporte y Contacto

** Panel Administrativo y Operativo (Back-office)
*** Dashboard Ejecutivo
**** Métricas de Ventas y Rendimiento por Vendedora
**** Monitoreo de Alertas de Reposición (Stock Crítico)
*** Gestión de Catálogo e Inventario
**** Mantenimiento CRUD de Prendas y Categorías
**** Parametrización de Variantes (Tallas, Colores y Stock)
**** Control de Visibilidad (Baja Lógica / Soft Delete)
*** Gestión de Pedidos y Logística (OMS)
**** Bandeja de Órdenes y Asignación de Vendedora
**** Verificación de Comprobantes de Pago
**** Control de Estados (Registrado, En Empaque, Despachado, Cancelado)
*** Administración de Personal
**** CRUD de Personal Operativo (Vendedoras)
**** Asignación de Roles y Bajas Lógicas de Cuentas
*** Configuración, Soporte y Auditoría
**** Mantenimiento de Preguntas Frecuentes (FAQ)
**** Visor Inmutable de Logs de Auditoría

@endmindmap
